release_config:
  input_release_path: ./releases/RFC0012345/RFC0012345.sql
  header_template_path: ./templates/header.sql
  footer_template_path: ./templates/footer.sql

  output_base_path: ./ddl
  dag_output_path: ./dags
  dag_template_path: ./templates/custom_dag_template.py



  object_type_map:
    table: tables
    view: views
    materialized_view: materialized_views
    function: functions
    procedure: procs
    external table: ext_tables
    writable external table: w_ext_tables


  options:
    skip_drop_statements: false
    encoding: utf-8

blocks:

  - name: ddl
    begin: --@@DDL_BEGIN {schema}.{object_name}
    end: --@@DDL_END
    output_path:
      template: "{base}/{location}/{database}/{schema}/{object_type}/{object_name}.sql"
      params: [base, location, database, schema, object_type, object_name]
    output_base_path: ${release_config.output_base_path}
    header_template_path: ${release_config.header_template_path}
    footer_template_path: ${release_config.footer_template_path}
    object_type_map: ${release_config.object_type_map}

  - name: model
    begin: --@@MODEL_BEGIN {schema}.{object_name} {dag_id}
    end: --@@MODEL_END
    output_path:
      template: "{base}/{location}/{database}/models/{dag_id}/create_{schema}_{object_name}.sql"
      params: [base, location, database, dag_id, schema, object_name]
    output_base_path: ${release_config.output_base_path}
    header_template_path: ${release_config.header_template_path}
    footer_template_path: ${release_config.footer_template_path}

  - name: loader
    begin: --@@LOADER_BEGIN {schema}.{object_name} {dag_id}
    end: --@@LOADER_END
    output_path:
      template: "{base}/{location}/{database}/models/{dag_id}/load_{schema}_{object_name}.sql"
      params: [base, location, database, dag_id, schema, object_name]
    output_base_path: ${release_config.output_base_path}
    header_template_path: ${release_config.header_template_path}
    footer_template_path: ${release_config.footer_template_path}

  - name: dag
    begin: --@@DAG_BEGIN {dag_id}
    end: --@@DAG_END
    output_path:
      template: "{dag_folder}/{dag_id}.py"
      params: [dag_folder, dag_id]
    dag_output_path: ${release_config.dag_output_path}
    dag_template_path: ${release_config.dag_template_path}